"""init

Revision ID: 79ffbf180482
Revises: 
Create Date: 2022-04-08 18:55:58.613407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ffbf180482'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=5), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=70), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('balance', sa.NUMERIC(), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=70), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###
